### ISSUE TITLE
Support for keyword args in Ruby 3

### ISSUE THREAD

**Issue by brunosedler** [makandra/memoized#6]
From Ruby 3 onwards, keyword args and hashes [can no longer be used interchangeably](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/). 
This leads to the issue, that this gem currently is not supporting memoizing methods with keyword arguments for Ruby 3.
In Ruby 2.7 you'll get the deprecation warning 
```
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/path/to/file/with/memoized/method.rb:<line>: warning: The called method `_unmemoized_<method_name>' is defined here
``` 

In Ruby 3 this will produce an error.

Example method that will break in Ruby 3:

```
memoize def foo(keyword_arg:)
  p keyword_arg
end
```

**Comment by triskweline** [comment]
This requires some refactoring as memoized preserves the `#arity` of memoized methods. This is required by some of our other gems, in particular consul.

This is the most painful method signature we can think of:

```ruby
def foo(a, b = "default-arg", *args, required_kwarg:, optional_kwarg: 'default', **kwargs)
  ...
end

method(:foo).parameters
=> [[:req, :a], [:opt, :b], [:rest, :args], [:keyreq, :required_kwarg], [:key, :optional_kwarg], [:keyrest, :kwargs]]
```

We could cover all cases with this:

```ruby
def cached_foo(a, b = UNIQUE, *args, required_kwarg:, optional_kwarg: Memoized::UNIQUE, **kwargs)
  # fixed code
  all_args = []
  all_kwargs = {}

  # one line per entry in #parameters  
  all_args.push(a)
  all_args.push(b) unless b.equal?(UNIQUE)
  all_args.push(*args)
  all_kwargs[:required_kwarg] = required_kwarg
  all_kwargs[:optional_kwarg] = optional_kwarg unless optional_kwarg.equal?(Memoized::UNIQUE)
  all_kwargs.merge!(kwargs)
  
  # fixed code
  cache_key = [all_args, all_kwargs]
  @_memoized_foo ||= {}
  
  if @_memoized_foo.key?(cache_key)
    @_memoized_foo[cache_key]
  else  
    live_result = original_foo(*all_args, **all_kwargs)
    @_memoized_foo[cache_key] = live_result
    live_result
  end
end
```

This would preserve both `#parameters` and `#arity` (current memoized only preserves `#arity`). We could also get rid of the long `if / elsif / elsif / else` and only have a single case that covers everything.
